### ISSUE TITLE
infix parser fails to parse "4**3", "4 ** 3"

### ISSUE THREAD

**Issue by davidpendergast** [davidpendergast/Cool-Python-Platformer#11]
#9

**Comment by davidpendergast** [comment]
also, "496 - 48*sin(0)" evaluates to 0 instead of 496. Looks like order of ops gets screwy with certain inputs

**Comment by a-johnston** [comment]
The second issue doesn't happen with my local changes, so that was likely fixed while working on a tangential issue. The first issue occurs due to *\* being parsed as two *'s and is a pretty serious oversight. Can you assign this issue to me?

**Comment by davidpendergast** [comment]
Probably simplest to just use '^' instead of '**' for exponentiation. And I'll write some more UTs to test the second issue if it seems to be fixed for you. 

I'll invite you as a collaborator and assign this issue to you when you accept.

**Comment by a-johnston** [comment]
Either changing the syntax or I am adding a check to see if there are two \* tokens parsed in a row. Your call.

**Comment by davidpendergast** [comment]
Let's use '**' to keep it consistent with python.

**Comment by a-johnston** [comment]
PR #12 fixes this
