### ISSUE TITLE
Remove uses of 'list' as a variable

### ISSUE THREAD

**Issue by a-johnston** [davidpendergast/Cool-Python-Platformer#7]
See: https://github.com/davidpendergast/Cool-Python-Platformer/blob/master/equations.py#L9
https://docs.python.org/2/library/functions.html#list

**Comment by a-johnston** [comment]
This is also an issue in `levels.py`

**Comment by davidpendergast** [comment]
Yeah I've been removing these as I come across them. Didn't realize using list, dict, string, etc. as var names was so problematic

**Comment by a-johnston** [comment]
nice. I'm writing a version of equations right now, not sure if it'll be totally compatible with how you're doing it, but I'll pr once it's decent

**Comment by davidpendergast** [comment]
+1 if it does infix notation
